name: Bug Report
description: Something not working?
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: |
        Describe the bug...

        Steps to reproduce:
        1. ...
        2. ...
    validations:
      required: true

  - type: input
    id: claude-version
    attributes:
      label: Claude Code Version
      description: Run `claude --version`
      placeholder: "1.0.0"
